[cmd_duration]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
ahead = "↑"
behind = "↓"
diverged = "↕"

[golang]
disabled = true

[buf]
disabled = true

[gcloud]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[nix_shell]
disabled = true

[rust]
disabled = true
